# Generated by Django 2.2.5 on 2020-04-04 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='Name',
            new_name='name',
        ),
    ]
