# Generated by Django 2.2.5 on 2020-04-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_auto_20200404_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='owner',
            field=models.TextField(default='lol wut'),
            preserve_default=False,
        ),
    ]
