# Generated by Django 2.2.5 on 2020-04-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0003_site_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='block_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField()),
                ('type_Name', models.CharField(max_length=30)),
                ('template', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='site',
            name='elements',
            field=models.TextField(),
        ),
    ]
