# Generated by Django 2.2.5 on 2020-04-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0004_auto_20200408_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
