# Generated by Django 2.2.5 on 2020-04-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0005_site_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('owner_site', models.CharField(max_length=30)),
                ('block_type', models.CharField(max_length=30)),
            ],
        ),
    ]
