# Generated by Django 2.2.5 on 2020-04-12 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0006_block'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block_type',
            old_name='type_Name',
            new_name='type_name',
        ),
    ]
