# Generated by Django 2.2.5 on 2020-04-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0007_auto_20200412_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='block_type',
            name='fields',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
