# Generated by Django 2.2.5 on 2020-05-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0008_block_type_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='site_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_site', models.CharField(max_length=30)),
                ('real_name', models.CharField(max_length=30)),
                ('Adress', models.URLField()),
                ('date_created', models.DateField()),
                ('owner', models.TextField()),
                ('views', models.IntegerField()),
            ],
        ),
    ]
