# Generated by Django 2.2.5 on 2020-05-14 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0009_site_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='site_data',
            new_name='site_data_table',
        ),
    ]
