# Generated by Django 2.2.5 on 2020-05-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0010_auto_20200514_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site_data_table',
            old_name='Adress',
            new_name='adress',
        ),
        migrations.AlterField(
            model_name='site_data_table',
            name='date_created',
            field=models.CharField(max_length=20),
        ),
    ]
