# Generated by Django 2.2.5 on 2020-05-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0011_auto_20200517_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
                ('image', models.ImageField(max_length=30, upload_to='')),
            ],
        ),
    ]
