# Generated by Django 2.2.5 on 2020-05-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0012_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='owner_element',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='owner_site',
            field=models.CharField(default='1', max_length=30),
            preserve_default=False,
        ),
    ]
