# Generated by Django 2.2.5 on 2020-05-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0013_auto_20200527_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='owner_element',
            new_name='element',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='tag',
            new_name='field',
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
