# Generated by Django 2.2.5 on 2020-05-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0014_auto_20200527_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
