# Generated by Django 2.2.5 on 2020-07-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0015_auto_20200527_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='debug',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
