# Generated by Django 2.2.5 on 2020-07-08 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0016_site_debug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='debug',
            new_name='final',
        ),
    ]
