# Generated by Django 2.2.5 on 2020-07-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0017_auto_20200708_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='block_type',
            name='official',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block_type',
            name='owner',
            field=models.CharField(default='sites-for-mc', max_length=30),
            preserve_default=False,
        ),
    ]
