# Generated by Django 2.2.5 on 2020-07-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0018_auto_20200714_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='name',
            field=models.CharField(default='1', max_length=30),
            preserve_default=False,
        ),
    ]
