# Generated by Django 2.2.5 on 2020-08-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0019_block_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block_type',
            name='official',
        ),
        migrations.AddField(
            model_name='block_type',
            name='modifier_type',
            field=models.CharField(default='normal', max_length=30),
            preserve_default=False,
        ),
    ]
