# Generated by Django 2.2.5 on 2020-04-04 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='site',
        ),
    ]
